/**
 * ERC725Y schema for the Celebrations app.
 * Keys are derived as keccak256(keyName) for Singleton types,
 * and follow LSP2 Array key encoding for Array types.
 *
 * This schema is consumed by erc725.js for encoding/decoding.
 */
export const CELEBRATIONS_SCHEMA = [
  {
    name: "CelebrationsVersion",
    key: "0x" + keccak256Hex("app:celebrations:version"),
    keyType: "Singleton",
    valueType: "string",
    valueContent: "String",
  },
  {
    name: "CelebrationsBirthday",
    key: "0x" + keccak256Hex("app:celebrations:birthday"),
    keyType: "Singleton",
    valueType: "string",
    valueContent: "String",
  },
  {
    name: "CelebrationsProfileCreatedAt",
    key: "0x" + keccak256Hex("app:celebrations:profileCreatedAt"),
    keyType: "Singleton",
    valueType: "uint256",
    valueContent: "Number",
  },
  {
    name: "CelebrationsEvents[]",
    key: "0x" + keccak256Hex("app:celebrations:events[]"),
    keyType: "Array",
    valueType: "bytes",
    valueContent: "JSONURL",
  },
  {
    name: "CelebrationsWishlist[]",
    key: "0x" + keccak256Hex("app:celebrations:wishlist[]"),
    keyType: "Array",
    valueType: "bytes",
    valueContent: "JSONURL",
  },
  {
    name: "CelebrationsSettings",
    key: "0x" + keccak256Hex("app:celebrations:settings"),
    keyType: "Singleton",
    valueType: "bytes",
    valueContent: "JSONURL",
  },
] as const;

/**
 * Synchronous keccak256 for key derivation.
 * Returns the 32-byte hex string WITHOUT the 0x prefix.
 * Uses a precomputed lookup for the keys used in this schema.
 */
function keccak256Hex(input: string): string {
  // These are the precomputed keccak256 hashes for the app's ERC725Y keys.
  // Run `npm run encode-keys` from the root to verify these values.
  const PRECOMPUTED: Record<string, string> = {
    // Generated by: npx hardhat run scripts/encodeERC725YKeys.ts
    "app:celebrations:version":
      "75c200d21c5803f487f69bb1a561017866d70d5d39c1c45d4604289bfdddb89a",
    "app:celebrations:birthday":
      "4645724f89f252a2307e2e9f2d5a5210c75e2d316688912008dd40b1735ff981",
    "app:celebrations:profileCreatedAt":
      "3ef1cb31cc2f82824c90cdb61b8cfc4897b52db62ea3583af3c484d1472e290c",
    "app:celebrations:events[]":
      "d6460ecddb5a675ad2a2a8b896e5ebad9bdb9944bb4e65e0de95a87d7075e76c",
    "app:celebrations:wishlist[]":
      "61c83ab9fb40ef42c1d905378ab7bbaace7254b88eaa277cddc640b189dbd4a0",
    "app:celebrations:settings":
      "900f36713dd8e8d81f42cdbc381011538edf5f9bcadb673979a9e54555b8121c",
  };

  if (PRECOMPUTED[input]) return PRECOMPUTED[input];

  // Fallback: runtime computation via TextEncoder + SubtleCrypto is async,
  // so we throw to catch misconfigurations early during development.
  throw new Error(
    `[erc725Keys] No precomputed key for "${input}". Run \`npm run encode-keys\` and update PRECOMPUTED.`
  );
}

// Export raw key hex strings for direct use in viem calls
export const KEY_VERSION = CELEBRATIONS_SCHEMA[0].key;
export const KEY_BIRTHDAY = CELEBRATIONS_SCHEMA[1].key;
export const KEY_PROFILE_CREATED_AT = CELEBRATIONS_SCHEMA[2].key;
export const KEY_EVENTS_ARRAY = CELEBRATIONS_SCHEMA[3].key;
export const KEY_WISHLIST_ARRAY = CELEBRATIONS_SCHEMA[4].key;
export const KEY_SETTINGS = CELEBRATIONS_SCHEMA[5].key;
